package com.example.currencyconverter.ContryCurrency

// Create a class to store the map.
class Currencies {
    val countries = mapOf(
        "United States" to "USD",
        "China" to "CNY",
        "Japan" to "JPY",
        "Germany" to "EUR",
        "United Kingdom" to "GBP",
        "India" to "INR",
        "France" to "EUR",
        "Brazil" to "BRL",
        "Italy" to "EUR",
        "Canada" to "CAD",
        "Mexico" to "MXN",
        "Russia" to "RUB",
        "Australia" to "AUD",
        "South Korea" to "KRW",
        "Saudi Arabia" to "SAR",
        "Spain" to "EUR",
        "Indonesia" to "IDR",
        "Turkey" to "TRY",
        "Argentina" to "ARS",
        "Netherlands" to "EUR",
        "Poland" to "PLN",
        "Colombia" to "COP",
        "Thailand" to "THB",
        "Iran" to "IRR",
        "Algeria" to "DZD",
        "Egypt" to "EGP",
        "Venezuela" to "VES",
        "Peru" to "PEN",
        "Ukraine" to "UAH",
        "Bangladesh" to "BDT",
        "Czech Republic" to "CZK",
        "Portugal" to "EUR",
        "Chile" to "CLP",
        "South Africa" to "ZAR",
        "Nigeria" to "NGN",
        "Sweden" to "SEK",
        "Norway" to "NOK",
        "Denmark" to "DKK",
        "Finland" to "EUR",
        "Greece" to "EUR",
        "Hungary" to "HUF",
        "Belgium" to "EUR",
        "Switzerland" to "CHF"
    )
}
